// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;

    /// <summary>Auto-generated class. Don't modify it! All your changes will be wiped with next update! Use Mods* partial methods instead for customization.</summary>
    [RequiresSkill(typeof(TailingRefiningSkill), 5)] 
    public partial class RefineWetTailingsLv2Recipe :
        RecipeFamily
    {
        public RefineWetTailingsLv2Recipe()
        {
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "RefineWetTailingsLv2",
                    Localizer.DoStr("Refine Wet Tailings Lv2"),
                    new IngredientElement[]
                    {
               new IngredientElement(typeof(WetTailingsItem), 8, typeof(TailingRefiningSkill)),  
                    },
                    new CraftingElement[]
                    {
               new CraftingElement<TailingsItem>(2),   
    
                    })
            };
            this.ExperienceOnCraft = 0.1f;  
            this.LaborInCalories = CreateLaborInCaloriesValue(200, typeof(TailingRefiningSkill));
            this.CraftMinutes = CreateCraftTimeValue(typeof(RefineWetTailingsLv2Recipe), 3, typeof(TailingRefiningSkill));
            this.ModsPreInitialize();
            this.Initialize(Localizer.DoStr("Refine Wet Tailings Lv2"), typeof(RefineWetTailingsLv2Recipe));
            this.ModsPostInitialize();
            CraftingComponent.AddRecipe(typeof(BlastFurnaceObject), this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }
}
